import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState, type ReactNode, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, RefreshCw, Globe, Monitor, UserRound, Code2, Folder, GraduationCap, Trophy, Mail, Github, Linkedin, Download, Heart, Star, ListTodo } from 'lucide-react';
import { Button } from '@/components/ui/button';
import desktopImage from '@/assets/retro-desktop.jpg';
import profileAsset from '@/assets/nitya-profile.jpg';
export const Route = createFileRoute('/')({ head: () => ({ meta: [
 { title: "Nitya Patel — Internet Corner" },
 { name: 'description', content: 'Nitya Patel’s retro internet corner: BTech CSE at Indus University, full stack and Python Essentials internships, and Odoo Hackathon 2026.' },
 { property: 'og:title', content: "Nitya Patel — Internet Corner" },
 { property: 'og:description', content: 'A Y2K-inspired personal portfolio celebrating learning, programming, and internet nostalgia.' },
 { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
] }), component: Portfolio });
const github='https://github.com/nityapatel7341';
const linkedin='https://www.linkedin.com/in/nitya-patel-4b135330b';
function Chrome() { return <span className="window-chrome" aria-hidden="true"><i>_</i><i>□</i><i>×</i></span>; }
function Window({ title, icon, children, id, pink=false, className='' }: { title:string; icon:ReactNode; children:ReactNode; id?:string; pink?:boolean; className?:string }) { return <section id={id} className={`window ${pink?'pink-window':''} ${className}`}><div className="window-title"><span className="title-label">{icon}{title}</span><Chrome /></div>{children}</section>; }
function Socials() { return <><Button asChild className="retro-button"><a href={github} target="_blank" rel="noopener noreferrer"><Github /> GitHub</a></Button><Button asChild className="retro-button"><a href={linkedin} target="_blank" rel="noopener noreferrer"><Linkedin /> LinkedIn</a></Button></>; }
function Portfolio() {
 const [clock,setClock]=useState('09:41 PM');
 const [draft,setDraft]=useState(false);
 useEffect(()=> { const timer=setInterval(()=>setClock(old=>old==='09:41 PM'?'09:42 PM':'09:41 PM'),60000); return ()=>clearInterval(timer); },[]);
 useEffect(()=> { if(window.matchMedia('(prefers-reduced-motion: reduce)').matches || window.matchMedia('(pointer: coarse)').matches) return; let last=0; const sparkle=(event:PointerEvent)=> { if(Date.now()-last<180)return; last=Date.now(); const star=document.createElement('span'); star.className='cursor-spark'; star.textContent='✦'; star.style.left=`${event.clientX}px`; star.style.top=`${event.clientY}px`; document.body.appendChild(star); setTimeout(()=>star.remove(),700); }; window.addEventListener('pointermove',sparkle); return ()=>window.removeEventListener('pointermove',sparkle); },[]);
 function saveDraft(event:FormEvent<HTMLFormElement>) { event.preventDefault(); const data=new FormData(event.currentTarget); const text=`Message for Nitya Patel\nFrom: ${data.get('name')}\nEmail: ${data.get('email')}\n\n${data.get('message')}\n\nDraft only — not sent.`; const url=URL.createObjectURL(new Blob([text],{type:'text/plain'})); const anchor=document.createElement('a'); anchor.href=url; anchor.download='message-for-nitya.txt'; anchor.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); setDraft(true); }
 return <div className="retro-page" id="top">
  <div className="browser-frame"><div className="browser-title"><span className="title-label"><Globe />Nitya's Internet Corner - Internet Explorer</span><Chrome /></div><div className="browser-menu" aria-hidden="true"><span>File</span><span>Edit</span><span>View</span><span>Favorites</span><span>Tools</span><span>Help</span></div><div className="browser-toolbar"><Button className="retro-button" aria-label="Back to top" title="Back to top" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><ArrowLeft /></Button><Button asChild className="retro-button" title="Go to about me"><a href="#about" aria-label="Go to about me"><ArrowRight /></a></Button><Button className="retro-button" aria-label="Refresh page" title="Refresh page" onClick={()=>window.location.reload()}><RefreshCw /></Button><span className="toolbar-caption">Address</span><div className="address-bar"><Globe size={13} /><span>http://nityapatel2006.com</span></div><span className="toolbar-caption">★ Go</span></div><div className="browser-status"><span>Done</span><span>Decorative address · not a live domain</span></div></div>
  <header className="page-banner"><span className="banner-star left" aria-hidden="true">✦</span><h1>★ WELCOME TO NITYA'S<br className="sm:hidden" /> INTERNET CORNER ★</h1><p>you have officially entered my website</p><span className="banner-star right" aria-hidden="true">✦</span></header>
  <nav className="site-nav" aria-label="Portfolio navigation">{[['about','ABOUT ME'],['skills','MY SKILLS'],['projects','PROJECTS'],['education','EDUCATION'],['achievements','ACHIEVEMENTS'],['contact','CONTACT']].map(([id,label])=><Button asChild className="retro-button" key={id}><a href={`#${id}`}>[ {label} ]</a></Button>)}</nav>
  <div className="ticker" aria-hidden="true"><span>★ welcome to my little corner of the world wide web ★ coding, learning & becoming ★ thanks for stopping by! ★ best viewed with a curious mind ★ welcome to my little corner of the world wide web ★ coding, learning & becoming ★ thanks for stopping by! ★ best viewed with a curious mind ★</span></div>
  <main className="page-main"><div className="desktop-layout"><aside className="sidebar" aria-label="Profile and retro widgets">
   <Window title="nitya.profile" icon={<UserRound />} pink className="profile-window"><div className="window-body"><div className="profile-picture"><img src={profileAsset} alt="Nitya Patel" width={800} height={800} /></div><h2 className="profile-name">Nitya Patel</h2><p className="profile-role">CSE Student ♡</p><div className="online">ONLINE NOW <span className="tiny-note">(decorative)</span></div><div className="profile-facts"><div><strong>Interests</strong>Web development & programming</div><div><strong>Currently obsessed with</strong>Internet nostalgia ★</div><div><strong>Currently learning</strong>Computer Science & Engineering</div><div><strong>My university</strong>Indus University</div></div><div className="mini-links"><Socials /></div></div></Window>
   <div className="construction"><span>🚧 UNDER<br />CONSTRUCTION 🚧</span></div><div className="side-sticker">I ♥ THE INTERNET<br />& MAKING THINGS</div>
   <Window title="visitor_counter.exe" icon={<Monitor />}><div className="window-body center-text"><p className="pixel text-xs">YOU ARE VISITOR</p><div className="counter" aria-label="Decorative visitor counter 0007341">{'0007341'.split('').map((n,i)=><span key={i}>{n}</span>)}</div><p className="tiny-note">Simulated counter, real appreciation ♡</p><div className="web-badges"><span>HTML INSIDE</span><span>WEB 1.0 FOREVER</span><span>BE NICE ONLINE</span></div></div></Window>
  </aside><div className="main-windows">
   <Window title="welcome.exe" icon={<Monitor />}><div className="welcome-scene"><img src={desktopImage} alt="Pixel-art green hills, clouds, a retro computer and a pink floppy disk" width={1536} height={1024} /><div className="welcome-overlay"><div className="window-title"><span className="title-label"><Star size={13} />a message from nitya</span><Chrome /></div><div className="welcome-message"><h2>HELLO INTERNET!!!</h2><p>I'm Nitya — a CSE student, coder and creative problem solver.</p><p>Welcome to my personal patch of cyberspace. Make yourself at home! ♡</p><Button asChild className="retro-button"><a href="#about">LET'S EXPLORE <ArrowRight /></a></Button></div></div></div><div className="welcome-status"><span>★ Personal website, big internet energy</span><span>Last updated: 05 Oct 2026</span></div></Window>
   <Window title="about_me.html" icon={<UserRound />} id="about" pink><div className="window-body"><div className="window-heading"><h2>☆ THE PERSON BEHIND THE PIXELS</h2><span>profile / about</span></div><p className="body-copy">Hello! I'm <strong>Nitya Patel</strong>, currently pursuing my <strong>BTech in Computer Science & Engineering at Indus University.</strong></p><p className="body-copy">My journey includes internships in <strong>Full Stack Web Development</strong> and <strong>Python Essentials</strong>, and participation in the <strong>Odoo Hackathon in 2026.</strong> This little website brings those chapters together.</p><div className="about-strip">♡ student life + code + a little internet nostalgia = my corner of the web</div></div></Window>
    <Window title="my_skills.txt" icon={<Code2 />} id="skills"><div className="window-body"><div className="window-heading"><h2>MY SKILL COLLECTION</h2><span>always learning</span></div><div className="skill-grid">{[['HTML','<>'],['CSS','{ }'],['JavaScript','JS'],['Java','☕'],['C++','++'],['SQL','▤']].map(([skill,icon])=><div className="skill-badge" key={skill}><b>{icon}</b><div>{skill}</div></div>)}</div><p className="skill-note">★ Experience: Full Stack Web Development internship · Python Essentials internship.</p></div></Window>
   </div></div>
   <div className="centered-sections">
   <Window title="my_projects / index.html" icon={<Folder />} id="projects"><div className="window-body"><div className="window-heading"><h2>THINGS I'M PUTTING ON THE WEB</h2><span>project folder</span></div><div className="project-grid"><article className="project-card"><div className="project-title"><Globe size={13} />internet_corner.html</div><div className="project-preview portfolio-preview"><Monitor /><span>★ NITYA'S INTERNET CORNER ★</span></div><div className="project-card-content"><h3>Personal Portfolio</h3><p>The retro personal website you're visiting right now.</p><div className="tech-tags"><span>React</span><span>Bootstrap 5</span><span>CSS</span><span>JavaScript</span></div><div className="project-actions"><Button asChild className="retro-button"><a href="#top">VIEW PROJECT</a></Button><Button className="retro-button" disabled title="Repository not provided">SOURCE CODE</Button></div></div></article><article className="project-card"><div className="project-title"><Folder size={13} />study_planner / main.py</div><div className="project-preview"><ListTodo /><span>★ STUDY PLANNER ★</span></div><div className="project-card-content"><h3>Study Planner CLI</h3><p>A Python command-line app to plan study sessions, track subjects and save tasks to a local file — a practice project from my Python Essentials internship.</p><div className="tech-tags"><span>Python</span><span>File I/O</span><span>CLI</span></div><div className="project-actions"><Button className="retro-button" disabled title="Live demo not hosted yet">VIEW PROJECT</Button><Button className="retro-button" disabled title="Repository not provided">SOURCE CODE</Button></div></div></article></div></div></Window>
   <Window title="education_and_experience.log" icon={<GraduationCap />} id="education" pink><div className="window-body"><div className="window-heading"><h2>MY LEARNING TIMELINE</h2><span>guestbook of growth</span></div>{[{title:'BTech · Computer Science & Engineering',text:'Indus University',meta:'Currently pursuing',icon:<GraduationCap size={19} />},{title:'Full Stack Web Development',text:'Internship',meta:'Completed',icon:<Code2 size={19} />},{title:'Python Essentials',text:'Internship',meta:'Completed',icon:<Code2 size={19} />}].map(item=><article className="timeline-entry" key={item.title}><div className="timeline-icon">{item.icon}</div><div><h3>{item.title}</h3><p>{item.text}</p><small>{item.meta}</small></div></article>)}</div></Window>
   <Window title="achievements / badge_collection" icon={<Trophy />} id="achievements"><div className="window-body"><div className="window-heading"><h2>CHAPTERS WORTH COLLECTING</h2><span>no invented trophies</span></div><div className="achievement-grid"><article className="achievement"><Trophy /><h3>Odoo Hackathon</h3><p>Participant · 2026</p></article><article className="achievement"><Code2 /><h3>Full Stack Internship</h3><p>Completed experience</p></article><article className="achievement"><GraduationCap /><h3>Python Essentials</h3><p>Completed internship</p></article></div></div></Window>
   <Window title="new_message / inbox" icon={<Mail />} id="contact"><div className="window-body"><div className="window-heading"><h2>LEAVE ME A MESSAGE!!!</h2><span>compose a draft</span></div><form className="mail-form" onSubmit={saveDraft}><div className="mail-field"><label htmlFor="sender-name">Name:</label><input id="sender-name" name="name" placeholder="Your name" required maxLength={100} /></div><div className="mail-field"><label htmlFor="sender-email">Email:</label><input id="sender-email" name="email" type="email" placeholder="you@example.com" required maxLength={254} /></div><div className="mail-field"><label htmlFor="sender-message">Message:</label><textarea id="sender-message" name="message" placeholder="Hello Nitya…" required maxLength={5000} /></div><p className="tiny-note">Email me directly at <a href="mailto:nityapatel.24.cse@iite.indusuni.ac.in">nityapatel.24.cse@iite.indusuni.ac.in</a>, or use EMAIL ME to open your mail app with my address filled in. SEND / SAVE DRAFT only downloads a copy to your device.</p><div className="mail-footer"><Button className="retro-button" type="submit"><Download />SEND / SAVE DRAFT</Button><Button asChild className="retro-button"><a href="mailto:nityapatel.24.cse@iite.indusuni.ac.in"><Mail />EMAIL ME</a></Button><div className="flex flex-wrap gap-2"><Socials /></div></div>{draft&&<p className="draft-status" role="status">Your message draft was downloaded. It has not been sent. Email it to nityapatel.24.cse@iite.indusuni.ac.in or connect on LinkedIn to share it.</p>}</form></div></Window>
   </div></main>
   <footer className="retro-footer">★ thanks for visiting my internet corner ★<br />© 2026 Nitya Patel · made for the world wide web<br /><Heart size={13} className="inline" /> stay curious, be kind, keep building <Heart size={13} className="inline" /></footer>
  <div className="taskbar"><a href="#top" className="taskbar-start"><Monitor size={15} />start</a><span className="taskbar-tab">🌐 Nitya's Internet Corner</span><span className="taskbar-clock" title="Simulated computer clock">◷ {clock}</span></div>
 </div>;
}
